In [11]:
#Function to genarate key for encryption with replace
keypath='datafiles/key.txt'
def genarate(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
            if i<6:
                f.write(str(i)+ ' '+str(i+4)+'\n')
            else:
                f.write(str(i)+ ' '+str(i-6)+'\n')
        return
genarate(keypath)

In [34]:
def dictkeyfile(keyfile):
    key={}
    with open(keyfile,"r") as f:
        for line in f:
            line=line.split()
            key[line[0]]=line[1]
    return key    
#def encryptmarks(datafile,keyfile):
dictkeyfile(keypath)


{'0': '4',
 '1': '5',
 '2': '6',
 '3': '7',
 '4': '8',
 '5': '9',
 '6': '0',
 '7': '1',
 '8': '2',
 '9': '3'}

In [33]:
def encryptmarksdata(datafile,keyfile):
    key=dictkeyfile(keyfile)
    with open(datafile,'r') as f:
        filedata=f.read().split('\n')
        #print(filedata)
    with open("datafiles/encrypted.txt",'w') as f:
        for mark in filedata:
            line = ''
            for n in mark:
                #print(key)
                line += key[n]
            f.write(line + '\n')
datafile='datafiles/marks.txt'
keyfile='datafiles/key.txt'      
encryptmarksdata(datafile,keyfile)       

In [57]:
def decryptmarksdata(datafile,keyfile):
    key=dictkeyfile(keyfile)
    newkey={}
    for key,value in key.items():
        newkey[value]=key
    print(newkey)
        
    with open(datafile,'r') as f:
        filedata=f.read().split('\n')
        #print(filedata)
    with open("datafiles/decrypted.txt",'w') as f:
        for mark in filedata:
            line=''
            for n in mark:
                    line+=newkey[n]
            f.write(line+'\n')
    return 
datafile='datafiles/encrypted.txt'
keyfile='datafiles/key.txt'      
decryptmarksdata(datafile,keyfile)       

{'4': '0', '5': '1', '6': '2', '7': '3', '8': '4', '9': '5', '0': '6', '1': '7', '2': '8', '3': '9'}


### Numpy 
- Proccessing N-Dimensional array



In [7]:
import numpy as np
li=[1,2,3,'z']
a=np.array(li)
a
b=np.arange(15)
b
rn=np.random.randint(1,10,10)
rn

array([5, 6, 7, 4, 3, 7, 3, 5, 7, 1])

In [16]:
m3=np.random.randint(1,50,size=(3,3))

m3

array([[25, 37, 46],
       [35, 12,  8],
       [41, 40, 33]])

In [17]:
m3[2][2]

33

In [32]:
m3.ndim
m3.size
m3.shape
m3.ndim
m3.dtype
m3.nbytes
m3.itemsize
m3[2,-1]
m3[-5:]
m3[::-1,::-1]
print(m3[:2,:2])

[[25 37]
 [35 12]]


In [40]:
d=np.random.randint(1,10,size=(3,3))
c=d+1
c

array([[10,  4,  6],
       [ 6, 10,  3],
       [ 4,  6, 10]])

In [48]:
import numpy as np
import timeit
st=timeit.default_timer()
m=np.ones((3,3))
print(m)
print(timeit.default_timer()-st)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0.0012700899997071247


### Pandas
- data cleaning 
- data transformation 
- data Analysis
## Notation 
- Series 
- Dataframe


In [19]:
import pandas as ps
internal1={'s1':12,'s2':18,'s3':24}
internal1=ps.Series(internal1)
internal2={'s1':15,'s2':20,'s3':21}
internal2=ps.Series(internal2)
final={'internal1':internal1,'internal2':internal2}
final=ps.DataFrame(final)
final

internal1  internal2
s1         12         15
s2         18         20
s3         24         21

In [25]:
## DataFrames
final["internal1"].head(1) ## top elements
final["internal1"].tail(1) ## bottum elements

s3    24
Name: internal1, dtype: int64

In [28]:
final.columns

Index(['internal1', 'internal2'], dtype='object')

In [30]:
final.values[2]

array([24, 21], dtype=int64)

In [31]:
final.head

<bound method NDFrame.head of     internal1  internal2
s1         12         15
s2         18         20
s3         24         21>

In [41]:
final.loc[3]=[26,4]
final

internal1  internal2
s1         12         15
s2         18         20
s3         24         21
s4         26          4
3          26          4

In [42]:
final.drop(3)

internal1  internal2
s1         12         15
s2         18         20
s3         24         21
s4         26          4

In [40]:
final

internal1  internal2
s1         12         15
s2         18         20
s3         24         21
s4         26          4

In [51]:
final.values[2]=[21,24]
final

internal1  internal2
s1         12         15
s2         18         20
s3         21         24
s4         26          4

In [55]:
r=ps.read_csv("datafiles/income.csv")
r

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [56]:
#Extract data 
r['2013']

0    41381
1    61137
2    50602
3    39919
4    57528
Name: 2013, dtype: int64

In [57]:
r.values

array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 47215, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)

In [59]:
for i in r.values:
    print(i[1],":",i[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [72]:
s=0
for i in range(5):
    s+=r.values[i][-2]
s/len(r.values[2][2:])

27799.333333333332